package io.github.hddq.restoid.ui.screens

import androidx.compose.animation.animateContentSize
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.combinedClickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.OpenInNew
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalUriHandler
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.mikepenz.aboutlibraries.Libs
import io.github.hddq.restoid.R

@Composable
fun LicensesScreen(onNavigateUp: () -> Unit, modifier: Modifier = Modifier) {
    val context = LocalContext.current

    // Load the libraries generated by the Gradle plugin
    val libs = remember {
        try {
            val jsonString = context.resources.openRawResource(R.raw.aboutlibraries)
                .bufferedReader()
                .use { it.readText() }
            Libs.Builder().withJson(jsonString).build()
        } catch (e: Exception) {
            Libs.Builder().build()
        }
    }

    val libraries = remember(libs) { libs.libraries.sortedBy { it.name } }

    LazyColumn(
        modifier = modifier.fillMaxSize(),
        verticalArrangement = Arrangement.spacedBy(8.dp),
        contentPadding = PaddingValues(16.dp)
    ) {
        // 1. Custom Items (Restoid & Restic)
        item {
            LicenseCard(
                name = "Restoid",
                author = "hddq",
                licenseName = "GPL-3.0",
                licenseText = Licenses.RESTOID_LICENSE,
                url = "https://github.com/hddq/restoid/blob/master/LICENSE"
            )
        }
        item {
            LicenseCard(
                name = "Restic",
                author = "Alexander Neumann",
                licenseName = "BSD-2-Clause",
                licenseText = Licenses.RESTIC_LICENSE,
                url = "https://github.com/restic/restic/blob/master/LICENSE"
            )
        }

        // 2. Auto-generated Gradle dependencies
        items(libraries) { library ->
            val firstLicense = library.licenses.firstOrNull()
            val licenseUrl = firstLicense?.url ?: ""
            val website = library.website ?: ""

            // Prioritize License URL, fallback to website
            val primaryUrl = if (licenseUrl.isNotBlank()) licenseUrl else website

            LicenseCard(
                name = library.name,
                author = library.developers.firstOrNull()?.name ?: library.organization?.name ?: "Unknown",
                licenseName = firstLicense?.name ?: "Unknown License",
                licenseText = if (licenseUrl.isNotBlank()) "License URL: $licenseUrl" else if (website.isNotBlank()) "Project Website: $website" else "No link available",
                version = library.artifactVersion,
                url = primaryUrl
            )
        }
    }
}

@OptIn(ExperimentalFoundationApi::class)
@Composable
fun LicenseCard(
    name: String,
    author: String = "",
    licenseName: String = "",
    licenseText: String,
    version: String? = null,
    url: String = ""
) {
    var expanded by remember { mutableStateOf(false) }
    val uriHandler = LocalUriHandler.current
    val clipboardManager = LocalClipboardManager.current

    // Optimize text for preview
    val licensePreview = remember(licenseText) {
        if (licenseText.length > 200) {
            licenseText.trimIndent().take(200) + "... (tap to expand)"
        } else {
            licenseText.trimIndent()
        }
    }

    Card(
        modifier = Modifier
            .fillMaxWidth()
            .combinedClickable(
                onClick = { expanded = !expanded },
                onLongClick = {
                    // Copy to clipboard on long press
                    clipboardManager.setText(AnnotatedString("$name\n$url\n\n$licenseText"))
                }
            ),
        colors = CardDefaults.cardColors(
            containerColor = MaterialTheme.colorScheme.surfaceContainer
        )
    ) {
        Column(
            modifier = Modifier
                .padding(16.dp)
                .fillMaxWidth()
                .animateContentSize()
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.Top
            ) {
                Column(modifier = Modifier.weight(1f)) {
                    Text(name, style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                    if (author.isNotBlank()) {
                        Text(author, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.primary)
                    }
                    if (version != null) {
                        Text(version, style = MaterialTheme.typography.labelSmall, fontFamily = FontFamily.Monospace)
                    }
                }

                // Action buttons
                Row {
                    if (url.isNotBlank()) {
                        IconButton(
                            onClick = { uriHandler.openUri(url) },
                            modifier = Modifier.size(24.dp)
                        ) {
                            Icon(
                                imageVector = Icons.Default.OpenInNew,
                                contentDescription = "Open Link",
                                tint = MaterialTheme.colorScheme.onSurfaceVariant,
                                modifier = Modifier.size(16.dp)
                            )
                        }
                    }
                }
            }

            if (licenseName.isNotBlank()) {
                Spacer(Modifier.height(8.dp))
                Text(licenseName, style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
            }

            if (expanded || licenseText.isNotBlank()) {
                Spacer(Modifier.height(8.dp))
                Text(
                    text = if (expanded) licenseText.trimIndent() else licensePreview,
                    style = MaterialTheme.typography.bodySmall,
                    fontFamily = FontFamily.Monospace,
                    color = MaterialTheme.colorScheme.onSurface
                )

                if (expanded) {
                    Row(
                        modifier = Modifier.fillMaxWidth().padding(top = 8.dp),
                        horizontalArrangement = Arrangement.End
                    ) {
                        IconButton(
                            onClick = {
                                clipboardManager.setText(AnnotatedString("$name\n$url\n\n$licenseText"))
                            },
                            modifier = Modifier.size(32.dp)
                        ) {
                            Icon(
                                imageVector = Icons.Default.ContentCopy,
                                contentDescription = "Copy License",
                                tint = MaterialTheme.colorScheme.primary,
                                modifier = Modifier.size(18.dp)
                            )
                        }
                    }
                }
            }
        }
    }
}